name: nearby_city
description: A package to get nearby cities in Korea. Uses https://github.com/jwlim94/nearby_city_KR_data to get the data.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  http: ^1.2.0

dev_dependencies:
  test: any
